# Appointment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: microservices
  labels:
    app: appointment-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
        version: v1
    spec:
      serviceAccountName: appointment-service
      containers:
      - name: appointment-service
        image: ECR_REGISTRY/PROJECT_NAME-appointment-service:IMAGE_TAG
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi" 
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
      restartPolicy: Always