# Appointment Service
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: microservices
  labels:
    app: appointment-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: appointment-service