# Service Account for Appointment Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appointment-service
  namespace: microservices
  labels:
    app: appointment-service
automountServiceAccountToken: false