# Service Account for Patient Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patient-service
  namespace: microservices
  labels:
    app: patient-service
automountServiceAccountToken: false